### ISSUE TITLE
On change events not firing

### ISSUE THREAD

**Issue by kevingy** [sherif-elmetainy/angular-datepicker#1]
I have defined a date picker attached to an input box:

`    <input cadpDatePicker [(ngModel)]="startDate" [minDate]="startDate"
            (change)="onDateChange($event)" (dateClicked)="onDateChange($event)"
            (command)="onDateChange($event)"/>`

As seen, I have attempted to catch the following events:
(change)
(command)
(dateClicked)

In short, none of the event handlers are ever called - ever. I need to know when the date is changed either by entering a date in the input or selecting a date from the date picker.

What am I missing?

**Comment by sherif-elmetainy** [comment]
Hello. Thank you for your feedback. The `cadpDatePicker` directive does not expose `@Output` properties with names change, dateClicked or command. You may see `@Output` properties with those names in the source code, but they are defined on components that are used internally and are not exposed by the module.

If you want to get a method called when the date value changed, you use a setter to do the call.

For example
```typescript
private _startDate: Date;
public set startDate(val: Date) {
  this._startDate = val;
  onDateChange(val);
}
```

I am also open to suggestions if you think some events need to be added, I can start working on adding them in a future version.

**Comment by kevingy** [comment]
Thank you so much for your reply. Your code example works for me.

As far as adding events in future versions, I think that doing so would more closely match what is common in Angular. At this point, however, I'm happy with what I have working!
